import {Injectable} from '@angular/core';
import {Observable, of} from 'rxjs';
import {Doctor} from '../models/doctor.model';

@Injectable()
export class DoctorsService {
  public load(): Observable<Doctor[]> {
    return of([
      {
        id: 1,
        title: 'Dr.',
        firstname: 'Isabella',
        lastname: 'Lindner-Rodler',
        street: 'St. Veiter Ring 21',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 513232',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 2,
        title: 'Dr.',
        firstname: 'Peter',
        lastname: 'Mitterer',
        street: 'Fleischmarkt 9/2',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 56302',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 3,
        title: 'Dr. med. Univ.',
        firstname: 'Günther',
        lastname: 'Schmoly',
        street: 'Mozartstraße 34',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 211800',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 4,
        title: 'Dr.',
        firstname: 'Claudia',
        lastname: 'Mayr-Wiltschnigg',
        street: 'Lodengasse 37',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 210012',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 5,
        title: 'Dr.',
        firstname: 'Herbert',
        lastname: 'Oberweger',
        street: 'Auer-von-Welsbach-Straße 42',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 418970',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 6,
        title: 'Dr.',
        firstname: 'Wolfgang',
        lastname: 'Kühnl',
        street: 'Koschatstraße 8',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 501789',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 7,
        title: 'Dr.',
        firstname: 'Doris',
        lastname: 'Koschier',
        street: 'Adolf-Kolping-Gasse 18',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 511110',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 8,
        title: 'Dr.',
        firstname: 'Evelyn',
        lastname: 'Steinhart',
        street: 'Ebenthalerstraße 57',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 347003',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 9,
        title: 'Dr.',
        firstname: 'Wolfgang Herbert',
        lastname: 'Hackl',
        street: 'Getreidegasse 4',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 515053',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 10,
        title: 'Dr.',
        firstname: 'Alexander',
        lastname: 'Perchtold',
        street: 'Auer-von-Welsbach-Straße 27',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 43177',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 11,
        title: 'Dr.',
        firstname: 'Maja Brigitte',
        lastname: 'Kerber',
        street: 'St. Veiter Straße 69',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 440494',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 12,
        title: 'Dr. med.',
        firstname: 'Erfried',
        lastname: 'Pichler',
        street: 'Herbertstraße 10',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 511573',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 13,
        title: 'Dr.',
        firstname: 'Andrea',
        lastname: 'Haas-Jölli',
        street: 'Dr-Hermann-Gasse',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 514430',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 14,
        title: 'Dr.',
        firstname: 'Kergi',
        lastname: 'Leitgeb',
        street: 'Siebenhügelstraße 13/5',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0699 81436405',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 15,
        title: 'Dr.',
        firstname: 'Dietmar',
        lastname: 'Schumnik',
        street: 'Villacherstraße 47',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 23354',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 16,
        title: 'Dr.',
        firstname: 'Ralf',
        lastname: 'Berger',
        street: 'Ebenthalerstraße 198',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 340440',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 17,
        title: 'Dr.',
        firstname: 'Silvia',
        lastname: 'Kuschnig-Roth',
        street: 'Carolinenstraße 8',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 281485',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 18,
        title: 'Dr. med. Univ.',
        firstname: 'Edith',
        lastname: 'Bauer',
        street: 'Rosentalerstraße 94',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0463 21596',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 19,
        title: 'Dr.',
        firstname: 'Gerhard',
        lastname: 'Weinzierl',
        street: 'Humboldtstraße 47',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0699 12704212',
        lat: 123,
        long: 23,
        isWaypoint: false
      },
      {
        id: 20,
        title: 'Dr.',
        firstname: 'Sieglinde',
        lastname: 'Sorschag',
        street: 'St. Veiterstraße 41',
        postalCode: '9020',
        city: 'Klagenfurt',
        country: 'Austria',
        phone: '0664 4427605',
        lat: 123,
        long: 23,
        isWaypoint: false
      }
    ]);
  }
}
